apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/stable/gameservers/sdtd/
  - ../../base/stable/nextcloud/
  - ../../base/stable/gameservers/minecraft/atm9/
  - ../../base/stable/gameservers/minecraft/vanilla/

namePrefix: "a01a-"

patches:
  - path: ./patches/nextcloud-values.yaml
    target:
      kind: Application
      name: nextcloud
  - path: ./patches/sdtd-values.yaml
    target:
      kind: Application
      name: sdtd
  - path: ./patches/vanilla-minecraft.yaml
    target:
      kind: Application
      name: vanilla-minecraft
  - path: ./patches/atm9-minecraft.yaml
    target:
      kind: Application
      name: atm9-minecraft
