apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/stable/gameservers/sdtd/
  - ../../base/stable/nextcloud/

namePrefix: "a01-"

patches:
  - path: ./patches/nextcloud-values.yaml
    target:
      kind: Application
      name: nextcloud
  - path: ./patches/sdtd-values.yaml
    target:
      kind: Application
      name: sdtd