apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: 

# incubator
#- ../../appsincubator/pihole/

# stable
#- ../../appsstable/nextcloud/
- ../../appsstable/gameservers/minecraft/vanilla/
#- ../../appsstable/gameservers/minecraft/atm9/
#- ../../appsstable/gameservers/minecraft/rlcraft/
#- ../../appsstable/gameservers/web-rcon/

namePrefix: "b01a-"

patches:
  - path: ./patches/vanilla-minecraft.yaml
    target:
      kind: Application
      name: vanilla-minecraft
#  - path: ./patches/pihole-config.yaml
#    target:
#      kind: Application
#      name: pihole
#  - path: ./patches/atm9-minecraft.yaml
#    target:
#      kind: Application
#      name: atm9-minecraft
#  - path: ./patches/rlcraft-minecraft.yaml
#    target:
#      kind: Application
#      name: rlcraft-minecraft
#  - path: ./patches/nextcloud-values.yaml
#    target:
#      kind: Application
#      name: nextcloud
