apiVersion: v1
kind: Service
metadata:
  name: home-mck-service
  namespace: traefik
spec:
  ports:
    - port: 443
      targetPort: 443
  clusterIP: None
---
apiVersion: v1
kind: Endpoints
metadata:
  name: home-mck-service
  namespace: traefik
subsets:
  - addresses:
      - ip: 144.2.66.218
    ports:
      - port: 443