apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: immich-route-prod
  namespace: traefik
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`immich.mckensy.xyz`)
      kind: Rule
      services:
        - name: b01-home-mck-service
          port: 443

