apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: immich-route-prod
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostSNI(`*`)
      services:
        - name: b01-home-mck-service
          port: 443