apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: immich-route-prod
  namespace: traefik
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`immich.mckensy.xyz`)
      kind: Rule
      services:
        - name: home-mck-service
          scheme: https
          port: 443
          servers:
            - url: "144.2.66.218:443"
