apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: patch
spec:
  ignoreDifferences:
  - jsonPointers:
    - /spec/volumeName
    kind: PersistentVolumeClaim
  syncPolicy:
    syncOptions:
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
  destination:
    namespace: b02-paper-minecraft
  source:
    helm:
      valuesObject:
        serviceAnnotations:
          "lbipam.cilium.io/ips": "192.168.1.237"
        minecraftServer:
          motd: "§b❄ work in progress §b❄"
          maxTickTime: 60000
          difficulty: normal
          whitelist: McKency, icykhaye, Moffoso
          icon: "https://raw.githubusercontent.com/kubelize/kube-projects/refs/heads/dev/environments/home-mck/inventory/src/assets/minecraft-icyk-snow-icon.png"
          viewDistance: 12
          memory: "6144M"
          jvmXXOpts: "-XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true"
          pluginUrl:
            - https://hangar.papermc.io/ViaVersion/ViaVersion
            - https://hangar.papermc.io/pop4959/Chunky
            - https://hangar.papermc.io/GriefPrevention/GriefPrevention
            - https://hangar.papermc.io/EssentialsX/Essentials
            - https://hangar.papermc.io/Imperialroma10/FishRewards
            - https://hangar.papermc.io/Sprax/BetterChairs
            - https://hangar.papermc.io/Imperialroma10/Timber
            - https://hangar.papermc.io/Blue/BlueMap
          extraPorts:
            - name: bluemap
              containerPort: 8100
              protocol: TCP
              service:
                enabled: true
                embedded: false
                type: ClusterIP 
                port: 8100
                targetPort: 8100
              ingress:
                ingressClassName: nginx
                enabled: true
                annotations:
                  cert-manager.io/cluster-issuer: letsencrypt-prod-nginx
                hosts:
                  - name: map.icykhaye.xyz
                    path: /
                  - name: mc.icykhaye.xyz
                    path: /
                  - name: minecraft.icykhaye.xyz
                    path: /
                tls:
                  - secretName: map-tls
                    hosts:
                      - map.icykhaye.xyz
                      - mc.icykhaye.xyz
                      - minecraft.icykhaye.xyz
        resources:
          requests:
            cpu: 2000m
            memory: 6144Mi
          limits:
            cpu: 4000m
            memory: 8192Mi
        nodeSelector:
          kubernetes.io/hostname: "mck-wk2"

          
