apiVersion: apps/v1
kind: Deployment
metadata:
  name: debian-modify-pvc
  labels:
    app: debian-modify-pvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debian-modify-pvc
  template:
    metadata:
      labels:
        app: debian-modify-pvc
    spec:
      containers:
      - name: debian
        image: debian:latest
        command: ["/bin/sleep", "infinity"]  # Keeps the container running
        volumeMounts:
        - name: pvc-volume
          mountPath: /data/old
      volumes:
      - name: pvc-volume
        persistentVolumeClaim:
          claimName: existing-pvc # Name of your existing PVC.
--- # for swapping pv between namespaces
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: existing-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 60Gi
  volumeName: # Volume name goes here