apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: patch
spec:
  source:
    helm:
      valuesObject:
        nodeSelector: talos-fpk-216
        minecraftServer:
          motd: §b💀
          maxTickTime: 60000
          difficulty: hard
          whitelist: McKency, MyAngelLuminas, marcel727, da10m, TayaTheKing, HyruleTemple, Mystery_LuL, NeoxHurensohn, CellCraft
          icon: "https://raw.githubusercontent.com/kubelize/kube-projects/refs/heads/dev/environments/home-mck/inventory/src/assets/minecraft-atm9-icon.png"
          maxPlayers: 10
          jvmXXOpts: "-XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=32M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1"
          autoCurseForge:
            overridesSkipExisting: true
        serviceAnnotations:
          "lbipam.cilium.io/ips": "192.168.1.235"
        livenessProbe:
          initialDelaySeconds: 600

          

          
