apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: 

- ../../../addons/argocd/repositories/
- ../../../apps/stable/gameservers/web-rcon/
# - ../../../tenants/b01a/
- ../../../tenants/b01/
- ../../../tenants/b02/

