apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: 

  # incubator
  - ../../../base/incubator/home-assistant/

  # stable
  - ../../../base/stable/nextcloud/

patches:
  # - path: ./patches/pihole-config.yaml
  #   target:
  #     kind: Application
  #     name: pihole
  # - path: ./patches/vanilla-minecraft.yaml
  #   target:
  #     kind: Application
  #     name: vanilla-minecraft
  - path: ./patches/nextcloud-values.yaml
    target:
      kind: Application
      name: nextcloud
