apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: 

  # incubator
  - ../../../base/incubator/home-assistant/

  # stable
  - ../../../base/stable/nextcloud/
  - ../../../base/stable/gameservers/minecraft/atm9/
  - ../../../base/stable/gameservers/minecraft/vanilla/

patches:
  # - path: ./patches/pihole-config.yaml
  #   target:
  #     kind: Application
  #     name: pihole
  - path: ./patches/vanilla-minecraft.yaml
    target:
      kind: Application
      name: vanilla-minecraft
  - path: ./patches/atm9-minecraft.yaml
    target:
      kind: Application
      name: atm9-minecraft
  - path: ./patches/nextcloud-values.yaml
    target:
      kind: Application
      name: nextcloud
