apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-nginx
  name: immich
spec:
  tls:
  - hosts:
    - immich.mckensy.xyz
    secretName: immich-tls
  ingressClassName: nginx
  rules:
  - host: immich.mckensy.xyz
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rei-nginx
            port:
              number: 2283