apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud-dev
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: nextcloud
  source:
    repoURL: https://nextcloud.github.io/helm/
    targetRevision: 5.5.6
    chart: nextcloud
    helm:
      valuesObject: {}