apiVersion: v1
kind: Service
metadata:
  name: b02-minecraft1-external
  namespace: traefik
spec:
  ports:
    - port: 25565
      targetPort: 25565
  clusterIP: None
---
apiVersion: v1
kind: Endpoints
metadata:
  name: b02-minecraft1-external
  namespace: traefik
subsets:
  - addresses:
      - ip: 85.5.236.199
    ports:
      - port: 25565
