apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: 

# incubator
- ../../../apps/stable/immich/

# stable

nameSuffix: "-prod"

patches:
  - path: ./patches/immich.yaml
    target:
      kind: Application
      name: immich
